# This workflow ensures that PR authors have acknowledged and reviewed the code suggestions made by the PR agent
# by checking if the author has marked a self-review checkbox in the comments and approves the PR if it is checked.

name: Verify Author Self-Review

on:
  # Since `issue_comment` cannot directly trigger a PR workflow, this must be done via the main branch workflow.
  issue_comment:
    types: [edited]

jobs:
  verify-author-self-review:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Author self-review in comments and Approve PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;

            if (!context.payload.issue.pull_request) {
              console.log('This comment is not on a pull request.');
              return;
            }

            console.log(`Pull Request Number: ${issue_number}`);

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            const foundChecked = comments.some(comment =>
              comment.body.trim().includes('- [x]  **Author self-review**:')
            );

            console.log(`foundChecked: ${foundChecked}`);

            // Approve the pull request if the self-review is checked
            if (foundChecked) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: issue_number,
                event: 'APPROVE',
                body: 'Self-review checkbox is checked. Approving the PR.'
              });
              console.log('Pull request approved.');
            }
