# This workflow ensures that PR authors have acknowledged and reviewed the code suggestions made by the PR agent.

name: Verify Author Self-Review

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  verify-author-self-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Author self-review in comments
        id: check_bot_comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, issue } = context;
            const { data: comments } = await github.rest.issues.listComments({
              ...repo,
              issue_number: issue.number
            });

            let foundChecked = false;
            let foundUnchecked = false;

            comments.forEach(comment => {
              if (!comment.deleted) {
                const body = comment.body.trim();
                if (body.includes('- [x]  **Author self-review**:')) {
                  foundChecked = true;
                } else if (body.includes('- [ ]  **Author self-review**:')) {
                  foundUnchecked = true;
                }
              }
            });

            if (foundChecked) {
              console.log('Author self-review is checked.');
              core.setOutput('status', 'passed');
            } else if (foundUnchecked) {
              core.setFailed('Author self-review is not checked. Please check the self-review checkbox.');
            } else {
              console.log('Author self-review checkbox not found in comments. Skipping check.');
            }
