name: Check Reviewed Bot Suggestions Label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for reviewed-bot-suggestions label
        id: check-label
        run: |
          LABEL_NAME="reviewed-bot-suggestions"
          PR_LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          if echo "$PR_LABELS" | grep -q "$LABEL_NAME"; then
            echo "Label $LABEL_NAME found."
          else
            echo "Label $LABEL_NAME not found. Please add the label reviewed-bot-suggestions to indicate you have reviewed the bot suggestions."
            exit 1
          fi
