# This GitHub Action workflow ensures that the author of a PR acknowledges PR bot suggestions by adding an emoji to their comments.
# In the past, bugs found during QA were often already suggested to be fixed by the review bot but were ignored.
# While the review bot may have false positives, it is beneficial to review its suggestions to double-check for potential issues.

name: PR Bot Suggestions Emoji Check

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR author
        run: |
          PR_AUTHOR=$(jq -r '.issue.user.login' "$GITHUB_EVENT_PATH")
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV

      - name: Find bot comment
        id: find-bot-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: "## PR Code Suggestions ✨"

      - name: Check for author acknowledgment
        run: |
          BOT_COMMENT_ID=${{ steps.find-bot-comment.outputs.comment-id }}
          if [ -z "$BOT_COMMENT_ID" ]; then
            echo "No bot comment found, skipping."
            exit 0
          fi

          COMMENTS_URL=$(jq -r '.issue.comments_url' "$GITHUB_EVENT_PATH")
          COMMENTS=$(curl -s $COMMENTS_URL)

          AUTHOR_COMMENT=$(echo "$COMMENTS" | jq -r --arg PR_AUTHOR "$PR_AUTHOR" --arg BOT_COMMENT "$BOT_COMMENT_ID" '.[] | select(.in_reply_to_id == ($BOT_COMMENT | tonumber)) | select(.user.login == $PR_AUTHOR).body')

          if [[ "$AUTHOR_COMMENT" =~ .*(:\+1:|:\-1:|:smile:|:tada:|:rocket:|:eyes:).* ]]; then
            echo "Emoji found in comment by PR author."
          else
              echo "No emoji found in comment by PR author. Please add an emoji to acknowledge the suggestions. In the past, bugs found during QA were often already suggested to be fixed by the review bot but were ignored. While the review bot may have false positives, it is beneficial to review its suggestions to double-check for potential issues."
            exit 1
          fi
