name: Verify Author Self-Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [edited]

jobs:
  verify-author-self-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Author self-review in comments and Create or Update Check Run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request ? context.payload.pull_request.number : context.payload.issue.number;

            let ref = '';
            if (context.payload.pull_request) {
              ref = context.payload.pull_request.head.sha;
            } else if (context.payload.issue && context.payload.issue.pull_request) {
              ref = context.sha;
            } else {
              console.log('This comment is not on a pull request.');
              return;
            }

            console.log(`Pull Request Number: ${issue_number}`);
            console.log(`HEAD SHA: ${ref}`);

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            let foundChecked = false;
            let foundUnchecked = false;

            comments.forEach(comment => {
              if (!comment.deleted) {
                const body = comment.body.trim();
                if (body.includes('- [x]  **Author self-review**:')) {
                  foundChecked = true;
                } else if (body.includes('- [ ]  **Author self-review**:')) {
                  foundUnchecked = true;
                }
              }
            });

            console.log(`foundChecked: ${foundChecked}, foundUnchecked: ${foundUnchecked}`);

            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref,
            });

            let checkRun = checkRuns.check_runs.find(run => run.name === 'Verify Author Self-Review' && run.head_sha === ref);

            const status = 'completed';
            let conclusion = 'failure';
            let summary = 'Author self-review is not checked. Please check the self-review checkbox in the Bot Review comment.';

            if (foundChecked) {
              conclusion = 'success';
              summary = 'Author self-review is checked.';
            }

            if (!checkRun) {
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'Verify Author Self-Review',
                head_sha: ref,
                status: status,
                conclusion: conclusion,
                output: {
                  title: 'Verify Author Self-Review',
                  summary: summary
                }
              });
              console.log('Check run created.');
            } else {
              await github.rest.checks.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: checkRun.id,
                status: status,
                conclusion: conclusion,
                output: {
                  title: 'Verify Author Self-Review',
                  summary: summary
                }
              });
              console.log('Check run updated.');
            }
