# https://github.com/renovatebot/github-action/
name: Renovate
on:
  schedule:
    - cron: "0 5 * * *" # Run daily at 5 AM
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_AUTODISCOVER: "true"
